// packages/simulator/src/react/components/device/bottom-bar.tsx
/** @jsxImportSource react */

import { ArrowUp, AudioLines, Mic, Plus, PlusCircle, SendHorizontal } from 'lucide-react'
import { type CSSProperties, useEffect, useRef, useState } from 'react'

interface BottomBarProps {
  isAndroid: boolean
  isDarkMode: boolean
  isPortrait: boolean
  onSendMessage: (text: string) => void
}

export const BottomBar = (props: BottomBarProps) => {
  const [isInputActive, setIsInputActive] = useState(false)
  const [userMessage, setUserMessage] = useState('')

  // Reference to the textarea element
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Effect to focus the textarea when isInputActive becomes true
  useEffect(() => {
    if (isInputActive && textareaRef.current) {
      // Focus the textarea after a small delay to ensure it's rendered
      setTimeout(() => (textareaRef.current as any)?.focus(), 0)
    }
  }, [isInputActive])

  // Function to send message and reset input
  const sendMessage = () => {
    if (!userMessage.trim()) return
    props.onSendMessage(userMessage)
    setUserMessage('')
    setIsInputActive(false)
  }

  const placeholder = (isAndroid: boolean) => (isAndroid ? 'RCS message' : 'Text Message ∙ RCS')

  return (
    <div
      style={
        {
          position: 'absolute',
          backgroundColor: props.isDarkMode ? '#030712' : 'white',
          paddingBottom: '1rem',
          paddingTop: '0.5rem',
          bottom: '0',
          left: '0',
          right: '0',
          paddingLeft: '0.5rem',
          paddingRight: '0.5rem',
          display: 'flex',
          alignItems: 'flex-end',
          gap: '0.5rem',
          color: props.isAndroid ? (props.isDarkMode ? 'white' : 'black') : props.isDarkMode ? '#9ca3af' : '#6b7280',
        } as CSSProperties
      }
    >
      {!props.isAndroid && (
        <div
          style={
            {
              width: '3rem',
              height: '3rem',
              borderRadius: '50%',
              cursor: 'pointer',
              backgroundColor: props.isDarkMode ? '#27272a' : '#e5e7eb',
              marginLeft: '0.5rem',
              marginRight: '0.5rem',
            } as CSSProperties
          }
        >
          <Plus
            style={{
              width: '1.75rem',
              height: '1.75rem',
              marginLeft: '0.625rem',
              marginTop: '0.625rem',
              opacity: props.isDarkMode ? '1' : '0.7',
            }}
          />
        </div>
      )}

      <div
        style={{
          flexGrow: '1',
          borderRadius: props.isAndroid ? '1.5rem' : '2rem',
          display: 'flex',
          cursor: 'pointer',
          ...(props.isAndroid
            ? {
                backgroundColor: props.isDarkMode ? '#27272a' : '#f3f4f6',
                color: props.isDarkMode ? 'white' : 'black',
                paddingTop: '0.75rem',
                paddingBottom: '0.75rem',
                paddingLeft: '0.75rem',
                paddingRight: '0.75rem',
                alignItems: 'flex-end',
              }
            : {
                border: props.isDarkMode ? '1px solid #27272a' : '1px solid #d1d5db',
                paddingTop: '0.25rem',
                paddingBottom: '0.25rem',
                paddingLeft: '0.75rem',
                paddingRight: '0.25rem',
                justifyContent: 'space-between',
                alignItems: 'center',
                marginRight: '0.5rem',
              }),
        }}
        id="message-input"
        onClick={() => setIsInputActive(true)}
      >
        {props.isAndroid && (
          <PlusCircle
            style={{
              width: '1.5rem',
              height: '1.5rem',
              marginRight: '0.75rem',
              opacity: props.isDarkMode ? '1' : '0.7',
            }}
          />
        )}

        {isInputActive ? (
          <div style={{ flexGrow: '1', display: 'flex', alignItems: 'center' }}>
            <textarea
              ref={textareaRef}
              style={{
                width: '100%',
                border: '0',
                padding: '0',
                margin: '0',
                outline: 'none',
                backgroundColor: 'transparent',
                color: 'inherit',
                resize: 'none',
              }}
              value={userMessage}
              onChange={(e) => setUserMessage((e.target as any).value)}
              onKeyDown={(e) => {
                if (e.key === 'Enter' && !e.shiftKey) {
                  e.preventDefault()
                  sendMessage()
                }
                if (e.key === 'Escape') {
                  setIsInputActive(false)
                }
              }}
              placeholder={placeholder(props.isAndroid)}
              aria-label="Type a message"
              rows={1}
            />
          </div>
        ) : (
          <div>{placeholder(props.isAndroid)}</div>
        )}

        {/* IOS */}
        {!props.isAndroid && (
          <div
            style={{
              width: '2.5rem',
              height: '2.5rem',
              borderRadius: '50%',
              cursor: 'pointer',
              ...(isInputActive
                ? {
                    backgroundColor: props.isDarkMode ? '#dbeafe' : '#22c55e',
                    color: props.isDarkMode ? '#1e40af' : 'white',
                  }
                : {}),
            }}
          >
            {!isInputActive ? (
              <Mic
                style={{
                  width: '2rem',
                  height: '2rem',
                  opacity: '0.7',
                  paddingLeft: '0.5rem',
                  paddingTop: '0.5rem',
                  borderRadius: '50%',
                }}
              />
            ) : (
              <ArrowUp
                style={{
                  width: '2rem',
                  height: '2rem',
                  opacity: '0.7',
                  paddingLeft: '0.5rem',
                  paddingTop: '0.5rem',
                  borderRadius: '50%',
                }}
                onClick={sendMessage}
              />
            )}
          </div>
        )}
      </div>

      {/* ANDROID */}
      {props.isAndroid && (
        <div
          style={{
            width: '3rem',
            height: '3rem',
            borderRadius: '50%',
            cursor: 'pointer',
            ...(isInputActive
              ? {
                  backgroundColor: props.isDarkMode ? '#dbeafe' : '#1e40af',
                  color: props.isDarkMode ? '#1e40af' : 'white',
                }
              : {
                  backgroundColor: props.isDarkMode ? '#27272a' : '#f3f4f6',
                }),
          }}
        >
          {!isInputActive ? (
            <AudioLines
              style={{
                width: '2.25rem',
                height: '2.25rem',
                opacity: '0.7',
                paddingLeft: '0.75rem',
                paddingTop: '0.75rem',
              }}
            />
          ) : (
            <SendHorizontal
              style={{
                width: '2.25rem',
                height: '2.25rem',
                opacity: '0.7',
                paddingLeft: '0.75rem',
                paddingTop: '0.75rem',
              }}
              onClick={sendMessage}
            />
          )}
        </div>
      )}
    </div>
  )
}

// packages/simulator/src/lit/components/bottom-bar/bottom-bar.ts
import { css, html, LitElement } from 'lit'
import { customElement, property, state } from 'lit/decorators.js'

@customElement('rbx-bottom-bar')
export class BottomBar extends LitElement {
  @property({ type: Boolean })
  isAndroid = true

  @property({ type: Boolean })
  isDarkMode = false

  @property({ type: Boolean })
  isPortrait = true

  @property()
  onSendMessage?: (text: string) => void

  @state()
  private isInputActive = false

  @state()
  private userMessage = ''

  @state()
  private textareaRef?: HTMLTextAreaElement

  static styles = css`
    :host {
      display: block;
    }
    
    :host(.ios) {
      font-family: var(--font-family-sf-pro-display, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif);
    }
    
    :host(.android) {
      font-family: 'Roboto', 'Segoe UI', system-ui, sans-serif;
    }

    .bottom-bar {
      position: absolute;
      bottom: 0;
      left: 0;
      right: 0;
      padding: 0.5rem 0.5rem 1rem 0.5rem;
      display: flex;
      align-items: flex-end;
      gap: 0.5rem;
    }

    .bottom-bar.light {
      background-color: white;
      color: #6b7280;
    }

    .bottom-bar.dark {
      background-color: #030712;
      color: #9ca3af;
    }

    .bottom-bar.android {
      color: black;
    }

    .bottom-bar.android.dark {
      color: white;
    }

    .plus-button {
      width: 3rem;
      height: 3rem;
      border-radius: 50%;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
      margin: 0 0.5rem;
    }

    .plus-button.light {
      background-color: #e5e7eb;
    }

    .plus-button.dark {
      background-color: #27272a;
    }

    .input-container {
      flex-grow: 1;
      border-radius: 1.5rem;
      display: flex;
      cursor: pointer;
    }

    .input-container.android {
      border-radius: 1.5rem;
      align-items: flex-end;
      padding: 0.75rem;
    }

    .input-container.android.light {
      background-color: #f3f4f6;
      color: black;
    }

    .input-container.android.dark {
      background-color: #27272a;
      color: white;
    }

    .input-container.ios {
      border-radius: 2rem;
      justify-content: space-between;
      align-items: center;
      padding: 0.25rem 0.25rem 0.25rem 0.75rem;
      margin-right: 0.5rem;
      border: 1px solid #d1d5db;
    }

    .input-container.ios.dark {
      border-color: #27272a;
    }

    .circle-plus-icon {
      width: 1.5rem;
      height: 1.5rem;
      margin-right: 0.75rem;
      opacity: 0.7;
    }

    .input-area {
      flex-grow: 1;
      display: flex;
      align-items: center;
    }

    .textarea {
      width: 100%;
      border: 0;
      padding: 0;
      margin: 0;
      outline: none;
      background-color: transparent;
      color: inherit;
      resize: none;
      font-family: inherit;
      font-size: inherit;
    }

    .action-button {
      width: 2.5rem;
      height: 2.5rem;
      border-radius: 50%;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .action-button.ios.active {
      color: white;
    }

    .action-button.ios.active.light {
      background-color: #22c55e;
    }

    .action-button.ios.active.dark {
      background-color: #dbeafe;
      color: #1e40af;
    }

    .send-button {
      width: 3rem;
      height: 3rem;
      border-radius: 50%;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .send-button.android.active {
      color: white;
    }

    .send-button.android.active.light {
      background-color: #1e40af;
    }

    .send-button.android.active.dark {
      background-color: #dbeafe;
      color: #1e40af;
    }

    .send-button.android.inactive.light {
      background-color: #f3f4f6;
    }

    .send-button.android.inactive.dark {
      background-color: #27272a;
    }

    .icon {
      opacity: 0.7;
    }
  `

  updated(changedProperties: Map<string, any>) {
    if (changedProperties.has('isInputActive') && this.isInputActive && this.textareaRef) {
      setTimeout(() => {
        this.textareaRef?.focus()
      }, 0)
    }
    if (changedProperties.has('isAndroid')) {
      this.updateHostClasses()
    }
  }

  private getPlaceholder(): string {
    return this.isAndroid ? 'RCS message' : 'Text Message • RCS'
  }

  private activateInput() {
    this.isInputActive = true
  }

  private handleInput(e: Event) {
    const target = e.target as HTMLTextAreaElement
    this.userMessage = target.value
  }

  private handleKeyDown(e: KeyboardEvent) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      this.sendMessage()
    }
    if (e.key === 'Escape') {
      this.isInputActive = false
    }
  }

  private sendMessage() {
    if (!this.userMessage.trim() || !this.onSendMessage) return

    this.onSendMessage(this.userMessage)
    this.userMessage = ''
    this.isInputActive = false
  }

  private renderPlusIcon() {
    return html`
      <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M5 12h14"/>
        <path d="M12 5v14"/>
      </svg>
    `
  }

  private renderCirclePlusIcon() {
    return html`
      <svg class="circle-plus-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <circle cx="12" cy="12" r="10"/>
        <path d="M8 12h8"/>
        <path d="M12 8v8"/>
      </svg>
    `
  }

  private renderMicIcon() {
    return html`
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/>
        <path d="M19 10v2a7 7 0 0 1-14 0v-2"/>
        <line x1="12" x2="12" y1="19" y2="23"/>
        <line x1="8" x2="16" y1="23" y2="23"/>
      </svg>
    `
  }

  private renderArrowUpIcon() {
    return html`
      <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M18 15l-6-6-6 6"/>
      </svg>
    `
  }

  private renderAudioLinesIcon() {
    return html`
      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M2 10v3"/>
        <path d="M6 6v11"/>
        <path d="M10 3v18"/>
        <path d="M14 8v7"/>
        <path d="M18 5v13"/>
        <path d="M22 10v3"/>
      </svg>
    `
  }

  private renderSendHorizontalIcon() {
    return html`
      <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
        <path d="M7 11l12-2-12-2v4"/>
        <path d="M7 13l12 2-12 2v-4"/>
      </svg>
    `
  }

  connectedCallback() {
    super.connectedCallback()
    this.updateHostClasses()
  }

  private updateHostClasses() {
    if (this.isAndroid) {
      this.classList.add('android')
      this.classList.remove('ios')
    } else {
      this.classList.add('ios')
      this.classList.remove('android')
    }
  }

  render() {
    const bottomBarClass = `bottom-bar ${this.isDarkMode ? 'dark' : 'light'} ${this.isAndroid ? 'android' : 'ios'}`
    const plusButtonClass = `plus-button ${this.isDarkMode ? 'dark' : 'light'}`
    const inputContainerClass = `input-container ${this.isAndroid ? 'android' : 'ios'} ${
      this.isDarkMode ? 'dark' : 'light'
    }`
    const actionButtonClass = `action-button ios ${this.isInputActive ? 'active' : ''} ${
      this.isDarkMode ? 'dark' : 'light'
    }`
    const sendButtonClass = `send-button android ${this.isInputActive ? 'active' : 'inactive'} ${
      this.isDarkMode ? 'dark' : 'light'
    }`

    return html`
      <div class="${bottomBarClass}">
        ${
          !this.isAndroid
            ? html`
          <div class="${plusButtonClass}">
            ${this.renderPlusIcon()}
          </div>
        `
            : ''
        }

        <div class="${inputContainerClass}" @click=${this.activateInput}>
          ${this.isAndroid ? this.renderCirclePlusIcon() : ''}

          ${
            this.isInputActive
              ? html`
            <div class="input-area">
              <textarea
                class="textarea"
                .value=${this.userMessage}
                @input=${this.handleInput}
                @keydown=${this.handleKeyDown}
                placeholder="${this.getPlaceholder()}"
                ${(el: HTMLTextAreaElement) => {
                  this.textareaRef = el
                }}
              ></textarea>
            </div>
          `
              : html`
            <div>${this.getPlaceholder()}</div>
          `
          }

          ${
            !this.isAndroid
              ? html`
            <div class="${actionButtonClass}" @click=${this.isInputActive ? this.sendMessage : undefined}>
              ${this.isInputActive ? this.renderArrowUpIcon() : this.renderMicIcon()}
            </div>
          `
              : ''
          }
        </div>

        ${
          this.isAndroid
            ? html`
          <div class="${sendButtonClass}" @click=${this.isInputActive ? this.sendMessage : undefined}>
            ${this.isInputActive ? this.renderSendHorizontalIcon() : this.renderAudioLinesIcon()}
          </div>
        `
            : ''
        }
      </div>
    `
  }
}
