// packages/simulator/src/react/components/messages/standalone-card.tsx
import { CardContent } from './card-content.js'
import { OuterSuggestions } from './suggestions/Suggestions.js'
import type { ThreadEntry } from '../../../core/types.js'

interface StandaloneCardProps {
  message: ThreadEntry
  nextMessage: ThreadEntry
  isAndroid: boolean
  isDarkMode: boolean
  isPortrait: boolean
  onSendMessage: (payload: any) => void
}

// Helper to check if message is an agent message with richCard
const hasRichCard = (message: ThreadEntry): boolean => {
  if (!message) {
    return false
  }
  return (
    'agentMessage' in message &&
    (message as any).agentMessage?.contentMessage &&
    'richCard' in (message as any).agentMessage.contentMessage
  )
}

// Helper to check if message has a StandaloneCard
const hasRichCardStandalone = (message: ThreadEntry): boolean => {
  if (!hasRichCard(message)) return false
  if (!('agentMessage' in message)) return false
  const contentMessage = (message as any).agentMessage.contentMessage
  // @ts-ignore
  if (!('richCard' in contentMessage)) return false
  // @ts-ignore
  return !!(contentMessage.richCard && 'standaloneCard' in contentMessage.richCard)
}

export function StandaloneCard(props: StandaloneCardProps) {
  if (!hasRichCardStandalone(props.message)) {
    return null
  }

  const agentMessage = (props.message as any).agentMessage
  if (!agentMessage || !agentMessage.contentMessage) return null

  const contentMessage = agentMessage.contentMessage
  // @ts-ignore
  if (!('richCard' in contentMessage) || !contentMessage.richCard || !('standaloneCard' in contentMessage.richCard)) {
    return null
  }

  // @ts-ignore
  if (!('cardContent' in contentMessage.richCard.standaloneCard)) {
    return null
  }

  // @ts-ignore
  const { cardContent } = contentMessage.richCard.standaloneCard

  return (
    <div>
      <div
        style={{
          borderRadius: '0.75rem',
          overflow: 'hidden',
          backgroundColor: props.isDarkMode ? '#27272a' : '#f3f4f6',
        }}
      >
        <CardContent
          cardContent={cardContent}
          isAndroid={props.isAndroid}
          isDarkMode={props.isDarkMode}
          isPortrait={props.isPortrait}
          onSendMessage={props.onSendMessage}
        />
      </div>

      {!props.nextMessage && (
        <OuterSuggestions
          suggestions={contentMessage?.suggestions || []}
          isAndroid={props.isAndroid}
          isDarkMode={props.isDarkMode}
          isPortrait={props.isPortrait}
          onSendMessage={props.onSendMessage}
        />
      )}
    </div>
  )
}

// packages/simulator/src/lit/components/messages/standalone-card.ts
import { css, html, LitElement } from 'lit'
import { customElement, property } from 'lit/decorators.js'
import type { ThreadEntry } from '../../types/index.js'
import './card-content.js'
import './suggestions.js'

@customElement('rbx-standalone-card')
export class StandaloneCard extends LitElement {
  @property({ type: Object })
  message!: ThreadEntry

  @property({ type: Object })
  nextMessage?: ThreadEntry

  @property({ type: Boolean })
  isAndroid = true

  @property({ type: Boolean })
  isDarkMode = false

  @property({ type: Boolean })
  isPortrait = true

  @property()
  onSendMessage?: (payload: any) => void

  static styles = css`
    :host {
      display: block;
    }
    
    :host(.ios) {
      font-family: var(--font-family-sf-pro-display, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif);
    }
    
    :host(.android) {
      font-family: 'Roboto', 'Segoe UI', system-ui, sans-serif;
    }

    .card-container {
      display: flex;
      flex-direction: column;
    }

    .card-wrapper {
      border-radius: 0.75rem;
      overflow: hidden;
    }

    .card-wrapper.light {
      background-color: #f3f4f6;
    }

    .card-wrapper.dark {
      background-color: #27272a;
    }
  `

  private hasRichCard(): boolean {
    if (!this.message || !('agentMessage' in this.message)) return false

    const contentMessage = this.message.agentMessage.contentMessage
    return contentMessage && 'richCard' in contentMessage
  }

  private hasStandaloneCard(): boolean {
    if (!this.hasRichCard() || !('agentMessage' in this.message)) return false

    const contentMessage = this.message.agentMessage.contentMessage
    if (!('richCard' in contentMessage)) return false

    return 'standaloneCard' in contentMessage.richCard
  }

  private getCardContent() {
    if (!this.hasStandaloneCard() || !('agentMessage' in this.message)) return null

    const contentMessage = this.message.agentMessage.contentMessage
    if (!('richCard' in contentMessage) || !('standaloneCard' in contentMessage.richCard)) return null

    return contentMessage.richCard.standaloneCard.cardContent
  }

  private getSuggestions() {
    if (!('agentMessage' in this.message)) return []

    const contentMessage = this.message.agentMessage.contentMessage
    return (contentMessage as any)?.suggestions || []
  }

  connectedCallback() {
    super.connectedCallback()
    this.updateHostClasses()
  }

  updated(changedProperties: Map<string, any>) {
    if (changedProperties.has('isAndroid')) {
      this.updateHostClasses()
    }
  }

  private updateHostClasses() {
    if (this.isAndroid) {
      this.classList.add('android')
      this.classList.remove('ios')
    } else {
      this.classList.add('ios')
      this.classList.remove('android')
    }
  }

  render() {
    if (!this.hasStandaloneCard()) return null

    const cardContent = this.getCardContent()
    if (!cardContent) return null

    const suggestions = this.getSuggestions()
    const wrapperClass = `card-wrapper ${this.isDarkMode ? 'dark' : 'light'}`

    return html`
      <div class="card-container">
        <div class="${wrapperClass}">
          <rbx-card-content
            .cardContent=${cardContent}
            .isAndroid=${this.isAndroid}
            .isDarkMode=${this.isDarkMode}
            .isPortrait=${this.isPortrait}
            .onSendMessage=${this.onSendMessage}
          ></rbx-card-content>
        </div>

        ${
          !this.nextMessage
            ? html`
          <rbx-suggestions
            .suggestions=${suggestions}
            .isAndroid=${this.isAndroid}
            .isDarkMode=${this.isDarkMode}
            .isPortrait=${this.isPortrait}
            .onSendMessage=${this.onSendMessage}
            .isOuter=${true}
          ></rbx-suggestions>
        `
            : ''
        }
      </div>
    `
  }
}
